#cloud-config
chpasswd:
  list: |
    root:__TMOS_ADMIN_PASSWORD__
    admin:__TMOS_ADMIN_PASSWORD__
  expire: False
ssh_authorized_keys:
  - __BIGIP_SSH_AUTH_KEY__
tmos_static_mgmt:
  enabled: true
  icontrollx_trusted_sources: false
  ip: __BIGIP_MANAGEMENT_IP__
  gw: __BIGIP_MANAGEMENT_NEXT_HOP__
  mtu: __BIGIP_MANAGEMENT_MTU__
  post_onboard_enabled: true
  post_onboard_commands:
    - tmsh create net trunk bond0 interfaces replace-all-with { 1.1 1.2 }
    - tmsh create net trunk bond1 interfaces replace-all-with { 1.3 1.4 }
tmos_declared:
  enabled: true
  icontrollx_trusted_sources: false
  do_declaration:
    schemaVersion: 1.0.0
    class: Device
    async: true
    label: Cloudinit Onboarding
    Common:
      class: Tenant
      bigipSystem:
        class: System
        hostname: __BIGIP_HOSTNAME__
        autoPhonehome: false
      mgmtIp:
        class: ManagementIp
        address: __BIGIP_MANAGEMENT_IP__
      provisioningLevels:
        class: Provision
        ltm: nominal
      dnsServers:
        class: DNS
        nameServers:
          - __DNS_1__
          - __DNS_2__
      bond0:
        class: Trunk
        interfaces:
          - "1.1"
          - "1.2"
      bond1:
        class: Trunk
        interfaces:
          - "1.3"
          - "1.4"