#!/bin/bash

# Read IP from bond0 (private) and move to bridge with BIG-IP management port
export PRIVATE_INTERFACE=bond0
export PRIVATE_IP_ADDRESS=$(ip addr show $PRIVATE_INTERFACE | grep "inet " | awk '{print $2}' | cut -d'/' -f1)
export PRIVATE_IP_MASK=$(ip addr show $PRIVATE_INTERFACE | grep "inet " | awk '{print $2}' | cut -d'/' -f2)
export PRIVATE_NEXT_HOP=$(ip route show 10.0.0.0/8 | awk '{print $3}')

export PUBLIC_INTERFACE=bond1
export PUBLIC_IP_ADDRESS=$(ip addr show $PUBLIC_INTERFACE | grep "inet " | awk '{print $2}' | cut -d'/' -f1)
export PUBLIC_IP_MASK=$(ip addr show $PUBLIC_INTERFACE | grep "inet " | awk '{print $2}' | cut -d'/' -f2)
export PUBLIC_NEXT_HOP=$(ip route show default | awk '{print $3}')

export DNS_1=$(cat /etc/resolv.conf | grep -m 1 nameserver | awk '{ print $2 }')
export DNS_2=$(cat /etc/resolv.conf | grep -m 2 nameserver | tail -n1 | awk '{ print $2 }')

export SSH_AUTH_KEY=$(cat /root/.ssh/authorized_keys | grep -Ev "^#|^$")

export BIGIP_IMAGE_DOWNLOAD_PATH='https://s3.us-east.cloud-object-storage.appdomain.cloud/f5-adc-bigip-17.5.0-0.0.15.all-1slot-031025001-us-east'
export BIGIP_IMAGE_DOWNLOAD_IMAGE_NAME='BIGIP-17.5.0-0.0.15.ALL_1SLOT-031025001.qcow2'

export BIGIP_CLOUDINIT_ISO=/opt/F5Networks/onboarding/BIGIP_USER_DATA.iso
export BIGIP_INSTANCE_ID=bigipinstance1
export BIGIP_HOSTNAME=bigip1
export BIGIP_VM_NAME=BIG-IP-17-5
export BIGIP_VM_MEMORY=4194304
export BIGIP_VM_VCPUS=2
export BIGIP_SSH_AUTH_KEY=$SSH_AUTH_KEY
export BIGIP_MANAGEMENT_IP=10.120.92.159/26
export BIGIP_MANAGEMENT_NEXT_HOP=$PRIVATE_NEXT_HOP
export BIGIP_MANAGEMENT_MTU=1460

export TMOS_ADMIN_PASSWORD='F5Networks!'

