network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      nameservers:
        addresses:
          - __DNS_1__
          - __DNS_2__
      virtual-function-count: 1
    eth1:
      dhcp4: no
      dhcp6: no
      nameservers:
        addresses:
          - __DNS_1__
          - __DNS_2__
      virtual-function-count: 1
    eth2:
      dhcp4: no
      dhcp6: no
      nameservers:
        addresses:
          - __DNS_1__
          - __DNS_2__
      virtual-function-count: 1
    eth3:
      dhcp4: no
      dhcp6: no
      nameservers:
        addresses:
          - __DNS_1__
          - __DNS_2__
      virtual-function-count: 1
    vf1:
      link: eth0
      dhcp4: no
      dhcp6: no
    vf2:
      link: eth1
      dhcp4: no
      dhcp6: no
    vf3:
      link: eth3
      dhcp4: no
      dhcp6: no
    vf4:
      link: eth4
      dhcp4: no
      dhcp6: no
  bonds:
    bond0:
      interfaces:
        - eth0
        - eth2
      parameters:
        mode: 802.3ad
        lacp-rate: fast
        mii-monitor-interval: 100
        transmit-hash-policy: layer3+4
        all-slaves-active: true
        up-delay: 0
        down-delay: 0
    bond1:
      interfaces:
        - eth1
        - eth3
      addresses: [__PUBLIC_IP_ADDRESS__/__PUBLIC_IP_MASK__]
      gateway4: __PUBLIC_NEXT_HOP__
      nameservers:
        addresses:
          - __DNS_1__
          - __DNS_2__
      parameters:
        mode: 802.3ad
        lacp-rate: fast
        mii-monitor-interval: 100
        transmit-hash-policy: layer3+4
        all-slaves-active: true
        up-delay: 0
        down-delay: 0
  bridges:
    br0:
      addresses: [__PRIVATE_IP_ADDRESS__/__PRIVATE_IP_MASK__, __HOST_LINK_LOCAL_MANAGEMENT_IP__]
      interfaces: [bond0]
      nameservers:
        addresses:
          - __DNS_1__
          - __DNS_2__
      routes:
        - to: 10.0.0.0/8
          via: __PRIVATE_NEXT_HOP__
        - to: 161.26.0.0/16
          via: __PRIVATE_NEXT_HOP__
        - to: 166.8.0.0/14
          via: __PRIVATE_NEXT_HOP__
