#!/bin/bash

export script_dir=/opt/F5Networks/onboarding

# Source the installenv file
if [ -f "$script_dir/installenv" ]; then
  source "$script_dir/installenv"
else
  echo "Error: installenv file not found in $script_dir"
  exit 1
fi

stop